"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";
import ScrollTrigger from "gsap/ScrollTrigger";
import ScrollSmoother from "gsap-trial/ScrollSmoother";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "My Pofolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   useGSAP(() => {
     const tl = gsap.timeline({ repeat: -1, repeatDelay: 0.6 });
     tl.to(".rotate", {
       opacity: 0,
       y: 50,
       duration: 40,
       ease: "slow",
     }).to(
       ".rotate",
       {
         opacity: 1,
         y: 0,
         rotation: -360,
         duration: 40,
         ease: "slow",
       },
       "<"
     );
     
   }, []);

  return (
    <html lang="en">
      <body className="bg-black bg-grain">
        <div className="scroll-wrapper">
          <div className="smooth-content">
            {children}
            
          </div>
        </div>
        <Image
              src="/Ellipsebig.svg"
              width={730}
              height={500}
              className=" fixed -z-10 top-[-13%] left-[-5%] rotate"
              alt={""}
            />
            <Image
              src="/Ellipsesmall.svg"
              width={400}
              height={500}
              className="fixed -z-10 top-[50%] right-[-8%] rotate"
              alt={""}
            />
      </body>
    </html>
  );
}
